import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'et';

type Translations = {
  [key: string]: string | Translations;
};

const translations: Record<Language, Translations> = {
  en: {
    nav: {
      dashboard: 'Dashboard',
      tools: 'Tools',
      people: 'People',
      locations: 'Locations',
      assignments: 'Assignments',
      requests: 'Tool Requests',
      signOut: 'Sign Out',
    },
    dashboard: {
      title: 'Inventory Dashboard',
      welcome: 'Welcome',
      totalTools: 'Total Tools',
      available: 'Available',
      inUse: 'In Use',
      maintenance: 'Maintenance',
      totalPeople: 'Total People',
      totalLocations: 'Total Locations',
      activeAssignments: 'Active Assignments',
    },
    tools: {
      title: 'Tools',
      subtitle: 'Manage your tool inventory',
      addTool: 'Add Tool',
      editTool: 'Edit Tool',
      noTools: 'No tools yet. Add your first tool to get started.',
      name: 'Tool Name',
      description: 'Description',
      serialNumber: 'Serial Number',
      purchaseDate: 'Purchase Date',
      purchasePrice: 'Purchase Price',
      status: 'Status',
      location: 'Location',
      serial: 'Serial',
      purchased: 'Purchased',
      price: 'Price',
      deleteConfirm: 'Are you sure you want to delete this tool?',
      save: 'Save Tool',
      cancel: 'Cancel',
      available: 'available',
      in_use: 'in use',
      maintenance: 'maintenance',
      retired: 'retired',
      damaged: 'damaged',
      lost: 'lost',
    },
    maintenance: {
      title: 'Tools in Maintenance',
      subtitle: 'View and manage tools currently under maintenance',
      noTools: 'No tools in maintenance',
      noToolsDesc: 'All tools are in working condition',
      returnToService: 'Return to Service',
      returning: 'Returning...',
      noLocation: 'No location assigned',
    },
    invite: {
      title: 'Invite User',
      subtitle: 'Send an invitation link to a new user',
      inviteUser: 'Invite User',
      emailLabel: 'Email Address',
      emailPlaceholder: 'user@example.com',
      emailRequired: 'Email address is required',
      roleLabel: 'User Role',
      regularUser: 'Regular User',
      regularUserDesc: 'Can view and create tool requests',
      admin: 'Administrator',
      adminDesc: 'Full access to manage tools, people, and locations',
      generateLink: 'Generate Invitation Link',
      generating: 'Generating...',
      success: 'Invitation Created!',
      successDesc: 'Share the link below with the invited user',
      invitationLink: 'Invitation Link',
      copy: 'Copy',
      copied: 'Copied!',
      note: 'Note',
      noteDesc: 'This link expires in 7 days and can only be used once',
      error: 'Failed to create invitation',
    },
    damageCost: {
      title: 'Damage & Loss Costs',
      subtitle: 'Track accumulated costs from damaged and lost tools',
      noDamage: 'No damaged or lost tools',
      noDamageDesc: 'All tools are accounted for and in good condition',
      byUser: 'By User',
      byLocation: 'By Location',
    },
    people: {
      title: 'People',
      subtitle: 'Manage team members',
      addPerson: 'Add Person',
      editPerson: 'Edit Person',
      noPeople: 'No people yet. Add your first team member to get started.',
      name: 'Full Name',
      email: 'Email Address',
      phone: 'Phone Number',
      role: 'Role',
      deleteConfirm: 'Are you sure you want to delete this person?',
      save: 'Save Person',
      cancel: 'Cancel',
    },
    locations: {
      title: 'Locations',
      subtitle: 'Manage storage locations and warehouses',
      addLocation: 'Add Location',
      editLocation: 'Edit Location',
      noLocations: 'No locations yet. Add your first location to get started.',
      name: 'Location Name',
      description: 'Description',
      baseWarehouse: 'Base Warehouse',
      baseWarehouseHelp: 'Base warehouses appear first when returning tools',
      deleteConfirm: 'Are you sure you want to delete this location?',
      save: 'Save Location',
      cancel: 'Cancel',
    },
    assignments: {
      title: 'Assignments',
      subtitle: 'Track tool assignments and returns',
      assignTool: 'Assign Tool',
      active: 'Active',
      history: 'History',
      noActive: 'No active assignments.',
      noHistory: 'No assignment history yet.',
      tool: 'Tool',
      assignedTo: 'Assigned To',
      assignedAt: 'Assigned',
      returnedAt: 'Returned',
      condition: 'Condition',
      notes: 'Notes',
      returnTool: 'Return',
      selectTool: 'Select Tool',
      assignmentType: 'Assignment Type',
      toPerson: 'To Person',
      toLocation: 'To Location',
      selectPerson: 'Select Person',
      selectLocation: 'Select Location',
      deleteConfirm: 'Are you sure you want to delete this assignment?',
      assign: 'Assign Tool',
      cancel: 'Cancel',
      return: 'Return Tool',
      returnLocation: 'Return Location',
      returnCondition: 'Condition',
      good: 'Good',
      maintenanceCondition: 'Maintenance',
      damaged: 'Damaged',
      lost: 'Lost',
      describeDamage: 'Describe the damage *',
      describeWhat: 'Describe what happened *',
      maintenanceNotes: 'Maintenance notes *',
      damageOccurred: 'What damage occurred? Be specific...',
      maintenanceNeeded: 'What maintenance is needed? Be specific...',
      whenLastSeen: 'When and where was the tool last seen?',
      baseWarehouses: 'Base Warehouses',
      otherLocations: 'Other Locations',
    },
    requests: {
      title: 'Tool Requests',
      subtitle: 'Manage tool requests from team members',
      createRequest: 'Create Request',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      noPending: 'No pending requests.',
      noApproved: 'No approved requests.',
      noRejected: 'No rejected requests.',
      requestedBy: 'Requested by',
      requestedAt: 'Requested',
      processedAt: 'Processed',
      processedBy: 'Processed by',
      reason: 'Reason',
      approve: 'Approve',
      reject: 'Reject',
      deleteConfirm: 'Are you sure you want to delete this request?',
      newRequest: 'New Tool Request',
      requestReason: 'Request Reason',
      whyNeedTool: 'Why do you need this tool?',
      submit: 'Submit Request',
      cancel: 'Cancel',
    },
    auth: {
      signIn: 'Sign In',
      signUp: 'Sign Up',
      email: 'Email',
      password: 'Password',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      signInButton: 'Sign In',
      signUpButton: 'Sign Up',
      unauthorized: 'Access Denied',
      unauthorizedMessage: 'Your email is not authorized to access this system. Please contact an administrator.',
      loading: 'Loading...',
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      delete: 'Delete',
      edit: 'Edit',
      save: 'Save',
      cancel: 'Cancel',
      close: 'Close',
      add: 'Add',
      yes: 'Yes',
      no: 'No',
      search: 'Search',
      filter: 'Filter',
      selectOption: 'Select an option',
      noResults: 'No results found',
    },
  },
  et: {
    nav: {
      dashboard: 'Töölaud',
      tools: 'Tööriistad',
      people: 'Inimesed',
      locations: 'Asukohad',
      assignments: 'Ülesanded',
      requests: 'Tööriista Taotlused',
      signOut: 'Logi Välja',
    },
    dashboard: {
      title: 'Inventuuri Töölaud',
      welcome: 'Tere tulemast',
      totalTools: 'Tööriistad Kokku',
      available: 'Saadaval',
      inUse: 'Kasutuses',
      maintenance: 'Hooldus',
      totalPeople: 'Inimesed Kokku',
      totalLocations: 'Asukohad Kokku',
      activeAssignments: 'Aktiivsed Ülesanded',
    },
    tools: {
      title: 'Tööriistad',
      subtitle: 'Halda oma tööriistade inventuuri',
      addTool: 'Lisa Tööriist',
      editTool: 'Muuda Tööriista',
      noTools: 'Tööriistasid pole veel. Lisa oma esimene tööriist alustamiseks.',
      name: 'Tööriista Nimi',
      description: 'Kirjeldus',
      serialNumber: 'Seerianumber',
      purchaseDate: 'Ostukuupäev',
      purchasePrice: 'Ostuhind',
      status: 'Olek',
      location: 'Asukoht',
      serial: 'Seeria',
      purchased: 'Ostetud',
      price: 'Hind',
      deleteConfirm: 'Kas oled kindel, et soovid selle tööriista kustutada?',
      save: 'Salvesta Tööriist',
      cancel: 'Tühista',
      available: 'saadaval',
      in_use: 'kasutuses',
      maintenance: 'hooldus',
      retired: 'pensionile',
      damaged: 'kahjustatud',
      lost: 'kadunud',
    },
    maintenance: {
      title: 'Hoolduses Olevad Tööriistad',
      subtitle: 'Vaata ja halda hetkel hoolduses olevaid tööriistu',
      noTools: 'Hoolduses tööriistu pole',
      noToolsDesc: 'Kõik tööriistad on töökorras',
      returnToService: 'Tagasta Kasutusele',
      returning: 'Tagastan...',
      noLocation: 'Asukohta pole määratud',
    },
    invite: {
      title: 'Kutsu Kasutaja',
      subtitle: 'Saada kutselink uuele kasutajale',
      inviteUser: 'Kutsu Kasutaja',
      emailLabel: 'E-posti Aadress',
      emailPlaceholder: 'kasutaja@näide.ee',
      emailRequired: 'E-posti aadress on kohustuslik',
      roleLabel: 'Kasutaja Roll',
      regularUser: 'Tavaline Kasutaja',
      regularUserDesc: 'Saab vaadata ja luua tööriistataotlusi',
      admin: 'Administraator',
      adminDesc: 'Täielik juurdepääs tööriistade, inimeste ja asukohtade haldamiseks',
      generateLink: 'Loo Kutselink',
      generating: 'Loon...',
      success: 'Kutse Loodud!',
      successDesc: 'Jaga allolevat linki kutsutud kasutajaga',
      invitationLink: 'Kutselink',
      copy: 'Kopeeri',
      copied: 'Kopeeritud!',
      note: 'Märkus',
      noteDesc: 'See link aegub 7 päeva pärast ja seda saab kasutada ainult üks kord',
      error: 'Kutse loomine ebaõnnestus',
    },
    damageCost: {
      title: 'Kahju- ja Kaotuskulud',
      subtitle: 'Jälgi kahjustatud ja kadunud tööriistade kulusid',
      noDamage: 'Kahjustatud või kadunud tööriistu pole',
      noDamageDesc: 'Kõik tööriistad on arvel ja heas seisukorras',
      byUser: 'Kasutaja Järgi',
      byLocation: 'Asukoha Järgi',
    },
    people: {
      title: 'Inimesed',
      subtitle: 'Halda meeskonnaliikmeid',
      addPerson: 'Lisa Isik',
      editPerson: 'Muuda Isikut',
      noPeople: 'Inimesi pole veel. Lisa oma esimene meeskonnaliige alustamiseks.',
      name: 'Täisnimi',
      email: 'E-posti Aadress',
      phone: 'Telefoninumber',
      role: 'Roll',
      deleteConfirm: 'Kas oled kindel, et soovid selle isiku kustutada?',
      save: 'Salvesta Isik',
      cancel: 'Tühista',
    },
    locations: {
      title: 'Asukohad',
      subtitle: 'Halda ladustamiskohti ja ladusid',
      addLocation: 'Lisa Asukoht',
      editLocation: 'Muuda Asukohta',
      noLocations: 'Asukohti pole veel. Lisa oma esimene asukoht alustamiseks.',
      name: 'Asukoha Nimi',
      description: 'Kirjeldus',
      baseWarehouse: 'Baas Ladu',
      baseWarehouseHelp: 'Baaslaod kuvatakse esimesena tööriistade tagastamisel',
      deleteConfirm: 'Kas oled kindel, et soovid selle asukoha kustutada?',
      save: 'Salvesta Asukoht',
      cancel: 'Tühista',
    },
    assignments: {
      title: 'Ülesanded',
      subtitle: 'Jälgi tööriistade määramist ja tagastamist',
      assignTool: 'Määra Tööriist',
      active: 'Aktiivne',
      history: 'Ajalugu',
      noActive: 'Aktiivseid ülesandeid pole.',
      noHistory: 'Ülesannete ajalugu pole veel.',
      tool: 'Tööriist',
      assignedTo: 'Määratud',
      assignedAt: 'Määratud',
      returnedAt: 'Tagastatud',
      condition: 'Seisukord',
      notes: 'Märkmed',
      returnTool: 'Tagasta',
      selectTool: 'Vali Tööriist',
      assignmentType: 'Ülesande Tüüp',
      toPerson: 'Isikule',
      toLocation: 'Asukohta',
      selectPerson: 'Vali Isik',
      selectLocation: 'Vali Asukoht',
      deleteConfirm: 'Kas oled kindel, et soovid selle ülesande kustutada?',
      assign: 'Määra Tööriist',
      cancel: 'Tühista',
      return: 'Tagasta Tööriist',
      returnLocation: 'Tagastamise Asukoht',
      returnCondition: 'Seisukord',
      good: 'Hea',
      maintenanceCondition: 'Hooldus',
      damaged: 'Kahjustatud',
      lost: 'Kadunud',
      describeDamage: 'Kirjelda kahju *',
      describeWhat: 'Kirjelda, mis juhtus *',
      maintenanceNotes: 'Hoolduse märkmed *',
      damageOccurred: 'Milline kahju tekkis? Ole täpne...',
      maintenanceNeeded: 'Millist hooldust on vaja? Ole täpne...',
      whenLastSeen: 'Millal ja kus nähti tööriista viimati?',
      baseWarehouses: 'Baaslaod',
      otherLocations: 'Teised Asukohad',
    },
    requests: {
      title: 'Tööriista Taotlused',
      subtitle: 'Halda meeskonnaliikmete tööriista taotlusi',
      createRequest: 'Loo Taotlus',
      pending: 'Ootel',
      approved: 'Heaks Kiidetud',
      rejected: 'Tagasi Lükatud',
      noPending: 'Ootel taotlusi pole.',
      noApproved: 'Heaks kiidetud taotlusi pole.',
      noRejected: 'Tagasi lükatud taotlusi pole.',
      requestedBy: 'Taotleja',
      requestedAt: 'Taotletud',
      processedAt: 'Töödeldud',
      processedBy: 'Töötleja',
      reason: 'Põhjus',
      approve: 'Kiida Heaks',
      reject: 'Lükka Tagasi',
      deleteConfirm: 'Kas oled kindel, et soovid selle taotluse kustutada?',
      newRequest: 'Uus Tööriista Taotlus',
      requestReason: 'Taotluse Põhjus',
      whyNeedTool: 'Miks sa seda tööriista vajad?',
      submit: 'Esita Taotlus',
      cancel: 'Tühista',
    },
    auth: {
      signIn: 'Logi Sisse',
      signUp: 'Registreeru',
      email: 'E-post',
      password: 'Parool',
      dontHaveAccount: 'Pole kontot?',
      alreadyHaveAccount: 'On juba konto?',
      signInButton: 'Logi Sisse',
      signUpButton: 'Registreeru',
      unauthorized: 'Juurdepääs Keelatud',
      unauthorizedMessage: 'Sinu e-post pole volitatud sellele süsteemile juurde pääsema. Palun võta ühendust administraatoriga.',
      loading: 'Laadimine...',
    },
    common: {
      loading: 'Laadimine...',
      error: 'Viga',
      success: 'Õnnestus',
      delete: 'Kustuta',
      edit: 'Muuda',
      save: 'Salvesta',
      cancel: 'Tühista',
      close: 'Sulge',
      add: 'Lisa',
      yes: 'Jah',
      no: 'Ei',
      search: 'Otsi',
      filter: 'Filter',
      selectOption: 'Vali valik',
      noResults: 'Tulemusi ei leitud',
    },
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'et' || saved === 'en') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }

    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
